apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-backend
  template:
    metadata:
      labels:
        app: dev-backend
    spec:
      containers:
        - name: dev-backend
          image: myregistry.com/dev-backend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dev-backend-svc
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: dev-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-backend
  template:
    metadata:
      labels:
        app: prod-backend
    spec:
      containers:
        - name: prod-backend
          image: myregistry.com/prod-backend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prod-backend-svc
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: prod-backend
